### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by timadamson** [derekgreer/expectedObjects#10]
Is there plans to support .NET core?

**Comment by derekgreer** [comment]
Yes, I do plan to add support at some point.  I actually received a pull request for another library I support (nunit.specifications) to support .Net Core, but the reason I haven't done any work on adding the support has been due to the instability of the .Net Core tooling.  When the .Net Core tooling was released, it was based upon  .xproj and project.json files and had several issues such as not being able to reference .Net Core libraries targeting the .Net framework from non-core libraries targeting the same framework.  Additionally, the .Net Core team concluded that there was too much work involved in supporting all library types and so has decided to go back to MSBuild/.csproj files.  I'm not sure if they've quite updated to tooling yet, but I've been waiting until things stabilized before doing the work of adding in support for .Net Core.

**Comment by timadamson** [comment]
If you create a .Net Core library project that references .Net Standard then it can be used by both core and full framework apps. Such a library would remain binary compatible after the new build tools are released and if did choose to migrate then there would be no changes to code files. I can provide a pull request if you like?

**Comment by derekgreer** [comment]
The last time I tried to create a Unit Test project using .Net Core and MSpec (with Resharper) I ran into some support issues and had to revert to using the normal class libraries to host the specs which causes you to grapple with [this bug](https://github.com/aspnet/Tooling/issues/688).  I'll have to see where things stand now, as it's been several months back when I first started doing .Net Core stuff.

**Comment by dgg** [comment]
Any news on this?
I have a library that takes a dependency on `ExpectedObjects` and I want to support _.NETCore_.
As it stands now, I cannot do that unless I leave out the part of the library that depends on it. And that would be a real pity, because it is so useful.

**Comment by derekgreer** [comment]
I should be able to get to this soon.  I've been waiting on things to stabilize with respect to tooling.

**Comment by derekgreer** [comment]
done.
