### ISSUE TITLE
When using c#9 records, ShouldEqual is false, when in fact the objects are equal

### ISSUE THREAD

**Issue by jameswoodley-zoopla** [derekgreer/expectedObjects#36]
When using a c#9 record like

`public record TestObject(string Name, string Description)` should Equal seems to be failing

Test Ouput:
```
ExpectedObjects.ComparisonException
The expected object did not match the actual object.

The following issues were found:

1) ApiReadModel:

  Expected:
    ApiReadModel
    { 
        ApiId = "5ff5d9b4029d9c0046ce28ef",
        Name = "name-3bd5466d-55a9-4e40-aa14-d40679c0492b",
        AudienceIdentifier = "identifier-468e8fb1-715f-42f2-83b7-d781d63847ff",
        Scopes = new String[] { "do:something","do:something:else"},
        IncludePermissionsInScopeClaim = False,
        SkipConsentIfFirstPartyApp = False,
        AllowOfflineAccess = False,
        TokenLifetimeSeconds = 1734333
    }

  Actual:
    ApiReadModel
    { 
        ApiId = "5ff5d9b4029d9c0046ce28ef",
        Name = "name-3bd5466d-55a9-4e40-aa14-d40679c0492b",
        AudienceIdentifier = "identifier-468e8fb1-715f-42f2-83b7-d781d63847ff",
        Scopes = new String[] { "do:something","do:something:else"},
        IncludePermissionsInScopeClaim = False,
        SkipConsentIfFirstPartyApp = False,
        AllowOfflineAccess = False,
        TokenLifetimeSeconds = 1734333
    }
```

**Comment by derekgreer** [comment]
I just created a test for this, but did not see an issue.  Can you provide version of ExpectedObjects you're using along with a complete example?

Here's the example I just tried which was successful:

```csharp
    public class RecordSpecs
    {
        [Subject("Record Comparisons")]
        public class when_comparing_equal_record_types_for_equality
        {
            static Person _actual;
            static ExpectedObject _expected;

            static bool _result;

            Establish context = () =>
            {
                _expected = new Person {FirstName = "firstName", LastName = "lastName"}.ToExpectedObject();
                _actual = new Person {FirstName = "firstName", LastName = "lastName"};
            };

            It should_be_equal = () => _expected.ShouldEqual(_actual);
        }
  }

    public record Person
    {
        public string? FirstName { get; init; }
        public string? LastName { get; init; }
    }

```

**Comment by derekgreer** [comment]
The issue you're running into is that C# records define their own equality by overriding Equals() and ExpectedObjects respects an object's own definition of equality over any semantic equivalency by default.  You've defined a record with a string array property and the generated Equals() is performing a reference-based comparison rather than a value based comparison for that property.  That is to say, ExpectedObjects is saying the two instances don't match because ApiReadModel's overridden Equals() method says they don't match.

While it may be supposed that ExpectedObjects shouldn't use an object's definition of equality, this need becomes clear when you consider that the expected object may be a deeply nested hierarchy composing framework or 3rd-party library types for which you want to rely upon the type's built-in definition of equality.

While decoupling test-specific equality from the system under test is certainly a valid scenario, it is more common for the Expected Objects pattern to be used for types which do not define their own equality than types that do.  The library has always provided the ability to configure which strategies you want by using the supplied IConfigurationContext<T> and in this case removing the EqualsOverrideComparisonStrategy would effect the result for which your looking.  To make this easier, I've also introduced the ability to ignore object-defined equality in version 3.4.0 with the IgnoreEqualsOverride() method:

```
new SomeEntity{ ... }.ToExpectedObject(ctx => ctx.IgnoreEqualsOverride());
```

That said, the intent behind C# 9 records seems to be to create immutable reference types that behave like value types, thus the generation of the Equals() and GetHashcode() methods.  You _can_ create mutable record types that do not have value-based equality, but it seems to go against their purpose.

**Comment by jameswoodley-zoopla** [comment]
Perfect result, thanks so much for your prompt help!
