### ISSUE TITLE
Ignoring collection order during comparison

### ISSUE THREAD

**Issue by PaoloLaurenti** [derekgreer/expectedObjects#8]
It would be great to have the possibility to configure the comparison of collection objects in order to ignore the order of their elements.

When enabled, If all elements of the compared collections are equal but placed in a different order, the comparison should result successfull.

Here's an example of what I would like:

``` C#
var expected = new List<string> { "A", "B", "C" };
var actual = new List<string> { "B", "C", "A" };
expected.ToExpectedObject().Configure(x => x.IgnoreCollectionOrder()).ShouldEqual(actual);
```

**Comment by derekgreer** [comment]
This feature has been added and is available in version [2.0.0](https://www.nuget.org/packages/ExpectedObjects/2.0.0).

ExpectedObjects has been changed to ignore order by default.  Currently to do otherwise would require you to use ExpectedObjectBuilder and replace the strategy with the    OrdinalEnumerableComparisonStrategy.  I'll make this easier in a future release.

**Comment by derekgreer** [comment]
Version [2.1.0](https://www.nuget.org/packages/ExpectedObjects/2.1.0) now supports the following syntax for achieving the original comparison:
```
new { ... }
    .ToExpectedObject(ctx => ctx.UseOrdinalComparision());
```

**Comment by sethflowers** [comment]
Why is the default to ignore the order? I was very surprised to find this is how it works now. 

`new [] {1, 2}.ToExpectedObject().ShouldNotEqual(new[] {2, 1});`

I can see why sometimes I would want the order ignored, but in almost all cases, I care very much that the order is tested. I have many tests that specifically check the order of a collection. Those tests are no longer reliable since upgrading to this version. I had a false sense of security, which is _exactly_ what I don't want in unit tests. I'd rather not have to go modify thousands of tests to add code to set the default to be what should be the default anyway. 

I like this library a lot, but I think the default should be to compare the order, and allow an override to ignore the order. Certainly it is more common to want the order compared.

**Comment by derekgreer** [comment]
I apologize for the inconvenience this change has caused  you.  

It's been awhile since I introduced this change, but I believe the decision was made to not consider order by default based upon usage patterns I found to be frequent within projects I work with as well as being influenced by the defaults selected by competing libraries.

What one considers to be the most frequent use case is highly subjective and will depend upon your typical testing style and patterns.  In my own test suites, I've found myself writing far more tests which validate that a specific entity or entities were added, updated, or deleted than tests which validate a request for all items of a set with a specified ordering.  That isn't to say this isn't the most common case for your tests, but it would be difficult to make general statements about what is the most common for all users of the library.

Unfortunately I don't know of a way for you to avoid modifying tests that depend upon the enumerable comparison semantics of the previous major semantic version of the library if you need strict ordering and want to use the latest version.
